# Generated by Django 2.0 on 2022-12-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='census',
            name='hola',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
