# Generated by Django 2.0 on 2022-12-01 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0002_census_hola'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='census',
            name='hola',
        ),
    ]
