# Generated by Django 2.0 on 2022-11-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0002_auto_20221124_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='census',
            name='type',
            field=models.CharField(choices=[('V', 'Voting'), ('BV', 'BinaryVoting')], default='V', max_length=2),
        ),
    ]
