# Generated by Django 2.0 on 2022-11-29 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0002_census_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='census',
            name='type',
        ),
    ]
