# Generated by Django 2.0 on 2022-12-07 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0003_remove_census_hola'),
        ('census', '0003_auto_20221124_1858'),
    ]

    operations = [
    ]
