# Generated by Django 2.0 on 2022-12-12 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0004_merge_20221207_1802'),
        ('census', '0003_remove_census_type'),
    ]

    operations = [
    ]
