# Generated by Django 2.0 on 2022-12-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0005_merge_20221212_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='census',
            name='type',
            field=models.CharField(choices=[('V', 'Voting'), ('BV', 'BinaryVoting')], default='V', max_length=2),
        ),
    ]
