# Generated by Django 2.0 on 2022-12-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorevoting',
            name='auths',
            field=models.ManyToManyField(related_name='scorevotings', to='base.Auth'),
        ),
    ]
