# Generated by Django 2.0 on 2022-11-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('YES OR NO TYPE', 'PREGUNTA DE SI O NO'), ('NORMAL QUESTION', 'PREGUNTA DE OPCIÓN MULTIPLE')], default='NORMAL QUESTION', max_length=55),
        ),
    ]
