# Generated by Django 2.0 on 2022-11-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_votingbinary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionoptionbinary',
            name='option',
            field=models.BooleanField(choices=[(1, 'Si'), (0, 'No')]),
        ),
    ]
