# Generated by Django 2.0 on 2022-11-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_auto_20221124_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='type',
            field=models.CharField(choices=[('V', 'Voting')], default='V', max_length=2),
        ),
        migrations.AddField(
            model_name='votingbinary',
            name='type',
            field=models.CharField(choices=[('BV', 'BinaryVoting')], default='BV', max_length=2),
        ),
    ]
