# Generated by Django 2.0 on 2022-12-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixnet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixnet',
            name='type',
            field=models.CharField(choices=[('V', 'Voting'), ('SV', 'ScoreVoting')], default='V', max_length=2),
        ),
    ]
