# Generated by Django 2.0 on 2022-12-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixnet', '0002_mixnet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mixnet',
            name='type',
            field=models.CharField(choices=[('V', 'Voting'), ('SV', 'ScoreVoting'), ('BV', 'BinaryVoting')], default='V', max_length=2),
        ),
    ]
