# Generated by Django 2.0 on 2022-12-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixnet', '0004_auto_20180605_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixnet',
            name='type',
            field=models.CharField(choices=[('V', 'Voting'), ('BV', 'BinaryVoting')], default='V', max_length=2),
        ),
    ]
