# Generated by Django 2.0 on 2022-12-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='type',
            field=models.CharField(choices=[('V', 'Voting'), ('SV', 'ScoreVoting')], default='V', max_length=2),
        ),
    ]
